
smile_platform_homepage_co:
    path:     /co
    defaults: { _controller: SmilePlatformBundle:Default:index }

Smile_platform_homepage:
  path:     /co
  defaults: { _controller: SmilePlatformBundle:Default:index }

smile_platform_profile:
  path: /profile/{userId}
  defaults: { _controller: SmilePlatformBundle:User:userProfile }

smile_platform_post:
  path: /post/{postId}
  defaults: { _controller: SmilePlatformBundle:Post:showPost }

smile_platform_contactUs:
  path: /contact
  defaults: { _controller: SmilePlatformBundle:Default:contact }

smile_platform_team:
  path: /team/{id}
  defaults: { _controller: SmilePlatformBundle:Team:team }

smile_platform_add_to_team:
  path: /addToTeam/{teamId}/{userId}
  defaults: { _controller: SmilePlatformBundle:Team:addToTeam }

smile_platform_leaveTeam:
  path: /leaveTeam/{teamId}
  defaults: { _controller: SmilePlatformBundle:Team:leaveTeam }

smile_platform_events:
  path: /events
  defaults: { _controller: SmilePlatformBundle:Event:seeAll }

smile_platform_event:
  path: /event/{eventId}
  defaults: { _controller: SmilePlatformBundle:Event:show }