<?php

namespace SkynetBundle\Repository;

/**
 * FacebookGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
