smile_api_getlastPosts:
    path:     /posts/getLastPosts
    defaults: { _controller: SmileApiBundle:Posts:getLastPosts }

smile_api_getOlderPosts:
  path: /getOlderPosts/{postId}
  defaults: { _controller: SmileApiBundle:Posts:getOlderPosts }
smile_api_getOlderPosts_url:
  path: /getOlderPosts/

smile_api_post_upvote:
  path: /post/upvote/{postId}
  defaults: { _controller: SmileApiBundle:Posts:upvote }
smile_api_post_upvote_url:
  path: /post/upvote/
  defaults: { _controller: SmileApiBundle:Posts:upvote }

smile_api_post_udownvote:
  path: /post/downvote/{postId}
  defaults: { _controller: SmileApiBundle:Posts:downvote }
smile_api_post_downvote_url:
  path: /post/downvote/
  defaults: { _controller: SmileApiBundle:Posts:downvote }

smile_api_comment_addNew:
  path: /comment/addNew
  defaults: { _controller: SmileApiBundle:Comment:newComment }

smile_api_admin_getstats:
  path: /admin/stats
  defaults: { _controller: SmileApiBundle:Admin:stats }

smile_api_post_addView:
  path: /post/addView/{postId}
  defaults: { _controller: SmileApiBundle:Posts:addViewToPost}

smile_api_post_addView_url:
  path: /post/addView/

smile_api_event_addUserComing:
  path: /event/iAmComing/{eventId}
  defaults: { _controller: SmileApiBundle:Event:attendAsMeToEvent}
smile_api_event_addUserComing_url:
  path: /event/iAmComing/
smile_api_event_addTeamComing:
  path: /event/teamComing/{eventId}/{teamId}
  defaults: { _controller: SmileApiBundle:Event:attendAsTeamToEvent}
smile_api_event_addTeamComing_url:
  path: /event/teamComing/
  defaults: { _controller: SmileApiBundle:Event:attendAsTeamToEvent}