smile_api_getlastPosts:
    path:     /posts/getLastPosts
    defaults: { _controller: SmileApiBundle:Posts:getLastPosts }

smile_api_post_upvote:
  path: /post/upvote/{postId}
  defaults: { _controller: SmileApiBundle:Posts:upvote }

smile_api_post_downvote:
  path: /post/downvote/{postId}
  defaults: { _controller: SmileApiBundle:Posts:downvote }