parameters:
    database_host: smilepainaseb.mysql.db
    database_port: null
    database_name: smilepainaseb
    database_user: smilepainaseb
    database_password: BatMan1939
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: b47ff8a4d708c564e3dd887eeacfe00d9bbc519e