# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: Smile\UserBundle\Security\Core\User\FOSUBUserProvider

services:
  my_user_provider:
    class: "%my_user_provider.class%"
    #this is the place where the properties are passed to the UserProvider - see config.yml
    arguments: ["@fos_user.user_manager",{facebook: facebook_id}]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    # Important! Tag this service or it wouldn't work
    tags:
        - { name: serializer.normalizer }

