<?php

namespace Smile\PlatformBundle\Repository;

/**
 * BackupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackupRepository extends \Doctrine\ORM\EntityRepository
{
}
