<?php

namespace Smile\PlatformBundle\Repository;
use Smile\PlatformBundle\Entity\Post;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsComment(Post $post)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.post = :post')
            ->setParameter('post', $post)
            ->orderBy('a.publicationDate', 'DESC')
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
