<?php

namespace Smile\PlatformBundle\Repository;

/**
 * EventProfilePicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventProfilePicRepository extends \Doctrine\ORM\EntityRepository
{
}
