<?php

namespace Smile\PlatformBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUpcomingEvents($numberOfEvents = 100)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.startingDate>:time')
            ->orderBy('a.startingDate', 'ASC')
            ->setMaxResults($numberOfEvents)
            ->setParameter('time', time());
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
