<?php

namespace Smile\PlatformBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastXPosts($numberOfPosts = 10)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->orderBy('a.creationTime', 'DESC')
            ->setMaxResults($numberOfPosts);
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
