<?php

namespace Smile\PlatformBundle\Repository;

/**
 * PostPicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPicRepository extends \Doctrine\ORM\EntityRepository
{
}
