<?php

namespace Smile\PlatformBundle\Repository;

/**
 * UpvoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpvoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkExist($user, $post)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.user = :user')
        ->andWhere('a.post = :post')
        ->setParameter('user', $user)
        ->setParameter('post', $post);
        $posts = $qb
            ->getQuery()
            ->getResult()
        ;
        if(count($posts)>0)
        {
            return true;
        }
        else
        {
            return false;
        }

    }
}
