<?php

namespace Smile\UserBundle\Repository;

/**
 * teamPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class teamPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
