<?php

namespace Smile\UserBundle\Repository;
use Smile\PlatformBundle\Entity\Team;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersByTeam(Team $team)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.teams', 't')
            ->where($qb->expr()->eq('t.id', $team->getId()));
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
